# Generated by Django 3.2.12 on 2022-02-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
        ('accounts', '0006_auto_20220216_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
